In [1]:
import pymcdm
import pyfdm
import numpy as np

PYMCDM

In [5]:
matrix = np.array([
    [4, 5, 6],
    [7, 5, 3],
    [8, 6, 3]
], dtype=float)
ctypes = np.array([-1, 1, 1])
weights = np.array([0.5, 0.23, 0.27])

In [7]:
try:
    prom = pymcdm.methods.PROMETHEE_II(preference_function='vshape_2')

    pref = prom(matrix, weights, ctypes, p=np.array([1, 1, 1], dtype=float), q=np.array([0, 0, 0], dtype=float))
    print(pref)
except: 
    print('error')

[ 0.655 -0.25  -0.405]


PYFDM

In [3]:
fmatrix = pyfdm.helpers.generate_fuzzy_matrix(3, 3)
fweights = pyfdm.weights.shannon_entropy_weights(fmatrix)
ftypes = np.array([-1, 1, 1])

print(fweights)

fcopras = pyfdm.methods.fCOPRAS()
fcopras(fmatrix, fweights, ftypes)

[[0.49783531 0.05321494 0.01448534]
 [0.30129524 0.48278851 0.50441901]
 [0.20086945 0.46399656 0.48109565]]


array([1.        , 0.39032769, 0.60855788])