In [2]:
import pymcdm
import pyfdm
import numpy as np

PYMCDM

In [6]:
matrix = np.array([[0.128, 0.363, 0.241],
       [0.195, 0.928, 0.485],
       [0.94 , 0.537, 0.918]])
ctypes = np.array([-1, -1, -1])
weights = np.array([0.5, 0.23, 0.27])

In [7]:
pymcdm.weights.cilos_weights(matrix, ctypes)

array([0.33333333, 0.        , 0.        , 0.        , 0.33333333,
       0.        , 0.        , 0.        , 0.33333333])

In [7]:
try:
    prom = pymcdm.methods.PROMETHEE_II(preference_function='vshape_2')

    pref = prom(matrix, weights, ctypes, p=np.array([1, 1, 1], dtype=float), q=np.array([0, 0, 0], dtype=float))
    print(pref)
except: 
    print('error')

[ 0.655 -0.25  -0.405]


PYFDM

In [3]:
fmatrix = pyfdm.helpers.generate_fuzzy_matrix(3, 3)
fweights = pyfdm.weights.shannon_entropy_weights(fmatrix)
ftypes = np.array([-1, 1, 1])

print(fweights)

fcopras = pyfdm.methods.fCOPRAS()
fcopras(fmatrix, fweights, ftypes)

[[0.49783531 0.05321494 0.01448534]
 [0.30129524 0.48278851 0.50441901]
 [0.20086945 0.46399656 0.48109565]]


array([1.        , 0.39032769, 0.60855788])

In [6]:
fmatrix = pyfdm.helpers.generate_fuzzy_matrix(3, 3)
fweights = pyfdm.weights.shannon_entropy_weights(fmatrix)
ftypes = np.array([-1, 1, 1])

print(fmatrix)
fspotis= pyfdm.methods.fSPOTIS()
bounds = fspotis.make_bounds(fmatrix)
bounds

[[[0.47252814 0.73575843 0.87686746]
  [0.13443454 0.29502807 0.68924954]
  [0.03022645 0.05474028 0.57439837]]

 [[0.75420558 0.90142598 0.91409894]
  [0.24737157 0.84565015 0.88577596]
  [0.08919675 0.26777436 0.33795227]]

 [[0.02565616 0.25777624 0.67672519]
  [0.32611029 0.75811252 0.81615681]
  [0.2481671  0.30141467 0.90100477]]]


array([[0.02565616, 0.91409894],
       [0.13443454, 0.88577596],
       [0.03022645, 0.90100477]])